version: '3'

services:
  web:
    build: ./web
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-db_django}
      - MYSQL_USER=${MYSQL_USER:-admin}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/django_store
    ports:
      - '8001:8001'
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-db_django}
      MYSQL_USER: ${MYSQL_USER:-admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-password}
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql